import type { ProductForScoring } from "./types"

// Generate mock products with varied data
export function generateMockProducts(): ProductForScoring[] {
  const products: ProductForScoring[] = [
    // High-performing mature product
    {
      product: {
        id: "prod-001",
        name: "Portable Espresso Maker",
        description: "Premium portable espresso machine for coffee enthusiasts",
        category: "Kitchen & Dining",
        tags: ["coffee", "portable", "premium"],
        phase: 2,
        createdAt: new Date("2023-01-15"),
        updatedAt: new Date("2024-12-05"),
      },
      externalSignals: {
        productId: "prod-001",
        searchVolume: 45000,
        searchTrendSlope: 0.35,
        keywordIntentRatio: 0.72,
        socialEngagementVelocity: 850,
        competitorReviewDepth: 1200,
        cpcEstimate: 2.8,
        sellerSaturation: 15,
      },
      economics: {
        productId: "prod-001",
        grossMarginPercent: 52,
        cogs: 28,
        landedCost: 35,
        categoryReturnRate: 8,
      },
      performance: {
        productId: "prod-001",
        unitsSold: 3800,
        sessions: 58000,
        conversionRate: 6.5,
        repeatPurchaseRate: 18,
        discountDependency: 15,
        periodStart: new Date("2024-10-01"),
        periodEnd: new Date("2024-11-30"),
      },
    },
    // Struggling idea-stage product
    {
      product: {
        id: "prod-002",
        name: "Smart Plant Watering System",
        description: "IoT-enabled automatic plant watering solution",
        category: "Home & Garden",
        tags: ["iot", "gardening", "automation"],
        phase: 0,
        createdAt: new Date("2024-11-01"),
        updatedAt: new Date("2024-12-05"),
      },
      externalSignals: {
        productId: "prod-002",
        searchVolume: 8200,
        searchTrendSlope: -0.12,
        keywordIntentRatio: 0.42,
        socialEngagementVelocity: 120,
        competitorReviewDepth: 3500,
        cpcEstimate: 4.2,
        sellerSaturation: 45,
      },
      economics: {
        productId: "prod-002",
        grossMarginPercent: 35,
        cogs: 42,
        landedCost: 52,
        categoryReturnRate: 22,
      },
    },
    // Early live product with potential
    {
      product: {
        id: "prod-003",
        name: "Minimalist Desk Organizer",
        description: "Bamboo desk organizer with wireless charging",
        category: "Office Supplies",
        tags: ["desk", "organization", "wireless-charging"],
        phase: 1,
        createdAt: new Date("2024-08-20"),
        updatedAt: new Date("2024-12-05"),
      },
      externalSignals: {
        productId: "prod-003",
        searchVolume: 22000,
        searchTrendSlope: 0.18,
        keywordIntentRatio: 0.65,
        socialEngagementVelocity: 420,
        competitorReviewDepth: 800,
        cpcEstimate: 1.8,
        sellerSaturation: 8,
      },
      economics: {
        productId: "prod-003",
        grossMarginPercent: 58,
        cogs: 18,
        landedCost: 22,
        categoryReturnRate: 5,
      },
      performance: {
        productId: "prod-003",
        unitsSold: 450,
        sessions: 12000,
        conversionRate: 3.8,
        repeatPurchaseRate: 8,
        discountDependency: 25,
        periodStart: new Date("2024-10-01"),
        periodEnd: new Date("2024-11-30"),
      },
    },
    // Mature product with margin issues
    {
      product: {
        id: "prod-004",
        name: "Premium Yoga Mat Set",
        description: "Eco-friendly yoga mat with accessories bundle",
        category: "Fitness & Wellness",
        tags: ["yoga", "fitness", "eco-friendly"],
        phase: 2,
        createdAt: new Date("2022-06-10"),
        updatedAt: new Date("2024-12-05"),
      },
      externalSignals: {
        productId: "prod-004",
        searchVolume: 65000,
        searchTrendSlope: 0.08,
        keywordIntentRatio: 0.68,
        socialEngagementVelocity: 1200,
        competitorReviewDepth: 4200,
        cpcEstimate: 3.5,
        sellerSaturation: 32,
      },
      economics: {
        productId: "prod-004",
        grossMarginPercent: 22,
        cogs: 38,
        landedCost: 45,
        categoryReturnRate: 12,
      },
      performance: {
        productId: "prod-004",
        unitsSold: 2200,
        sessions: 72000,
        conversionRate: 3.1,
        repeatPurchaseRate: 5,
        discountDependency: 45,
        periodStart: new Date("2024-10-01"),
        periodEnd: new Date("2024-11-30"),
      },
    },
    // Strong idea with good fundamentals
    {
      product: {
        id: "prod-005",
        name: "Modular Kitchen Storage System",
        description: "Stackable modular containers for kitchen organization",
        category: "Kitchen & Dining",
        tags: ["storage", "organization", "modular"],
        phase: 0,
        createdAt: new Date("2024-11-15"),
        updatedAt: new Date("2024-12-05"),
      },
      externalSignals: {
        productId: "prod-005",
        searchVolume: 38000,
        searchTrendSlope: 0.28,
        keywordIntentRatio: 0.75,
        socialEngagementVelocity: 650,
        competitorReviewDepth: 950,
        cpcEstimate: 2.2,
        sellerSaturation: 12,
      },
      economics: {
        productId: "prod-005",
        grossMarginPercent: 62,
        cogs: 15,
        landedCost: 19,
        categoryReturnRate: 6,
      },
    },
    // Early live with mixed signals
    {
      product: {
        id: "prod-006",
        name: "LED Night Light Projector",
        description: "Galaxy projector with Bluetooth speaker",
        category: "Home Decor",
        tags: ["lighting", "decor", "projector"],
        phase: 1,
        createdAt: new Date("2024-09-01"),
        updatedAt: new Date("2024-12-05"),
      },
      externalSignals: {
        productId: "prod-006",
        searchVolume: 52000,
        searchTrendSlope: 0.42,
        keywordIntentRatio: 0.58,
        socialEngagementVelocity: 1850,
        competitorReviewDepth: 5800,
        cpcEstimate: 5.2,
        sellerSaturation: 78,
      },
      economics: {
        productId: "prod-006",
        grossMarginPercent: 48,
        cogs: 22,
        landedCost: 28,
        categoryReturnRate: 18,
      },
      performance: {
        productId: "prod-006",
        unitsSold: 1200,
        sessions: 28000,
        conversionRate: 4.3,
        repeatPurchaseRate: 3,
        discountDependency: 38,
        periodStart: new Date("2024-10-01"),
        periodEnd: new Date("2024-11-30"),
      },
    },
  ]

  return products
}
